import { NextRequest, NextResponse } from "next/server";

export async function GET() {
  const riskState = {
    account_equity: 100000.0,
    daily_pnl: 1284.5,
    daily_loss_limit: 2000.0,
    daily_loss_limit_pct: 2.0,
    remaining_daily_budget: 3284.5, // 2000 + 1284.5
    portfolio_exposure: 18200.0,
    portfolio_exposure_pct: 18.2,
    max_portfolio_exposure: 30000.0,
    max_portfolio_exposure_pct: 30.0,
    exposure_utilization_pct: 60.7,
    trade_risk_pct: 0.31,
    max_trade_risk_pct: 1.0,
    max_trade_loss_limit: 1000.0,
    consecutive_losses: 0,
    max_consecutive_losses: 3,
    liquidity_spread_pct: 2.1,
    max_liquidity_spread_pct: 10.0,
    min_opportunity_score: 70,
    current_opportunity_score: 94,
    kill_switch: false,
    overall_status: "APPROVED",
    environment: "PAPER",
    trading_enabled: false, // Default fail-safe
    execution_engine_status: "READY",
    safety_gate_status: "ACTIVE",

    candidate_decision: {
      symbol: "SPY",
      strategy: "IRON_CONDOR",
      opportunity_score: 94,
      max_loss: 315.0,
      proposed_exposure: 1800.0,
      spread_pct: 2.1,
      decision: "APPROVED",
      reason: "RISK_APPROVED",
      timestamp: "2026-09-02 00:35:10 UTC",
      gates_passed: 7,
      total_gates: 7,
    },

    position_sizing: {
      equity: 100000.0,
      risk_fraction: 0.01,
      risk_budget: 1000.0,
      max_loss_per_contract: 315.0,
      calculated_quantity: 3,
      max_allowed_quantity: 5,
    },

    gates: [
      {
        id: "GATE-01",
        name: "Opportunity Score",
        condition: "Score >= 70",
        current_value: "94 / 100",
        limit: "70 Min",
        status: "PASS",
        source: "quant.alpha / RiskEngine",
        description: "Statistical IV/RV variance premium exceeds quant hurdle rate.",
      },
      {
        id: "GATE-02",
        name: "Max Trade Risk",
        condition: "Max Loss <= 1.0% ($1,000)",
        current_value: "0.31% ($315.00)",
        limit: "1.00% ($1,000)",
        status: "PASS",
        source: "RiskEngine.evaluate",
        description: "Single-trade maximum loss strictly capped at 1% of total portfolio equity.",
      },
      {
        id: "GATE-03",
        name: "Daily Loss Limit",
        condition: "Daily Loss < 2.0% ($2,000)",
        current_value: "+$1,284.50 (Profit)",
        limit: "-$2,000.00",
        status: "PASS",
        source: "RiskEngine.record_trade_result",
        description: "Automated circuit breaker halts trading if intraday drawdown touches 2%.",
      },
      {
        id: "GATE-04",
        name: "Portfolio Exposure",
        condition: "Exposure <= 30.0% ($30,000)",
        current_value: "18.2% ($18,200.00)",
        limit: "30.0% ($30,000)",
        status: "PASS",
        source: "RiskEngine.evaluate",
        description: "Total aggregate options collateral utilization constrained within 30%.",
      },
      {
        id: "GATE-05",
        name: "Market Liquidity",
        condition: "Option Bid-Ask Spread <= 10.0%",
        current_value: "2.1% Spread",
        limit: "10.0% Max",
        status: "PASS",
        source: "RiskEngine.check_liquidity",
        description: "Slippage containment verified across all 4 legs of candidate spread.",
      },
      {
        id: "GATE-06",
        name: "Consecutive Losses",
        condition: "Consecutive Losses < 3",
        current_value: "0 Losses",
        limit: "3 Losses Max",
        status: "PASS",
        source: "RiskEngine.consecutive_losses",
        description: "Enforces mandatory cooling period after 3 consecutive stop outs.",
      },
      {
        id: "GATE-07",
        name: "Emergency Kill Switch",
        condition: "Kill Switch Disengaged",
        current_value: "ARMED (Ready)",
        limit: "OFF",
        status: "PASS",
        source: "RiskEngine.kill_switch",
        description: "Hardware-level stop-autonomous-execution circuit is armed and operational.",
      },
    ],

    alerts: [
      {
        id: "ALT-101",
        timestamp: "00:35:10 UTC",
        severity: "INFO",
        title: "Opportunity Threshold Verified",
        message: "SPY Iron Condor opportunity score 94 exceeds minimum threshold 70.",
      },
      {
        id: "ALT-102",
        timestamp: "00:30:00 UTC",
        severity: "INFO",
        title: "Exposure Utilization Healthy",
        message: "Portfolio exposure at 18.2% ($18,200), utilizing 60.7% of maximum $30,000 limit.",
      },
      {
        id: "ALT-103",
        timestamp: "00:15:00 UTC",
        severity: "INFO",
        title: "Daily Risk Budget Positive",
        message: "Daily P&L stands at +$1,284.50. Risk buffer expanded to $3,284.50.",
      },
    ],

    history: [
      {
        id: "RSK-8941",
        timestamp: "2026-09-01 14:32:00 UTC",
        symbol: "SPY",
        strategy: "IRON_CONDOR",
        opportunity_score: 94,
        max_loss: "$315.00",
        exposure: "$1,800.00",
        decision: "APPROVED",
        failed_gate: "--",
        reason: "RISK_APPROVED",
      },
      {
        id: "RSK-8940",
        timestamp: "2026-08-28 10:15:00 UTC",
        symbol: "QQQ",
        strategy: "BULL_PUT_SPREAD",
        opportunity_score: 88,
        max_loss: "$390.00",
        exposure: "$1,925.00",
        decision: "APPROVED",
        failed_gate: "--",
        reason: "RISK_APPROVED",
      },
      {
        id: "RSK-8939",
        timestamp: "2026-08-27 15:40:00 UTC",
        symbol: "NVDA",
        strategy: "IRON_CONDOR",
        opportunity_score: 74,
        max_loss: "$260.00",
        exposure: "$2,600.00",
        decision: "BLOCKED",
        failed_gate: "Market Liquidity",
        reason: "SPREAD_TOO_WIDE (12.4% > 10.0%)",
      },
      {
        id: "RSK-8938",
        timestamp: "2026-08-25 11:10:00 UTC",
        symbol: "IWM",
        strategy: "BEAR_CALL_SPREAD",
        opportunity_score: 91,
        max_loss: "$405.00",
        exposure: "$1,215.00",
        decision: "APPROVED",
        failed_gate: "--",
        reason: "RISK_APPROVED",
      },
      {
        id: "RSK-8937",
        timestamp: "2026-08-22 09:35:00 UTC",
        symbol: "TSLA",
        strategy: "IRON_CONDOR",
        opportunity_score: 62,
        max_loss: "$450.00",
        exposure: "$2,250.00",
        decision: "BLOCKED",
        failed_gate: "Opportunity Score",
        reason: "OPPORTUNITY_SCORE_TOO_LOW (62 < 70)",
      },
    ],
  };

  return NextResponse.json(riskState);
}

export async function POST(request: NextRequest) {
  const body = await request.json().catch(() => ({ active: false }));
  return NextResponse.json({
    success: true,
    kill_switch: !!body.active,
    message: body.active ? "Kill Switch Activated" : "Kill Switch Reset",
  });
}
