export interface AssetMarketRecord {
  symbol: string;
  name: string;
  price: number;
  change: number;
  change_percent: number;
  high: number;
  low: number;
  volume: number;
  realized_volatility: number;
  implied_volatility: number;
  iv_rv_ratio: number;
  iv_premium: number;
  opportunity_score: number;
  market_regime: string;
  vol_signal: "EXPENSIVE" | "CHEAP" | "FAIR";
  strategy: string;
  market_status: string;
  last_updated: string;
}

export const SUPPORTED_ASSETS: Record<string, AssetMarketRecord> = {
  SPY: {
    symbol: "SPY",
    name: "SPDR S&P 500 ETF Trust",
    price: 591.42,
    change: 4.82,
    change_percent: 0.82,
    high: 592.65,
    low: 588.10,
    volume: 64230100,
    realized_volatility: 10.42,
    implied_volatility: 16.85,
    iv_rv_ratio: 1.62,
    iv_premium: 61.7,
    opportunity_score: 94,
    market_regime: "HIGH IV SPREAD",
    vol_signal: "EXPENSIVE",
    strategy: "IRON_CONDOR",
    market_status: "OPEN",
    last_updated: new Date().toISOString(),
  },
  QQQ: {
    symbol: "QQQ",
    name: "Invesco QQQ Trust (Nasdaq 100)",
    price: 498.75,
    change: 6.20,
    change_percent: 1.26,
    high: 501.10,
    low: 494.50,
    volume: 48910400,
    realized_volatility: 13.85,
    implied_volatility: 20.40,
    iv_rv_ratio: 1.47,
    iv_premium: 47.3,
    opportunity_score: 89,
    market_regime: "BULLISH EXPANSION",
    vol_signal: "EXPENSIVE",
    strategy: "BULL_PUT_SPREAD",
    market_status: "OPEN",
    last_updated: new Date().toISOString(),
  },
  IWM: {
    symbol: "IWM",
    name: "iShares Russell 2000 ETF",
    price: 222.18,
    change: -1.15,
    change_percent: -0.51,
    high: 224.00,
    low: 221.30,
    volume: 28400500,
    realized_volatility: 16.20,
    implied_volatility: 23.50,
    iv_rv_ratio: 1.45,
    iv_premium: 45.1,
    opportunity_score: 86,
    market_regime: "BEARISH ROTATION",
    vol_signal: "EXPENSIVE",
    strategy: "BEAR_CALL_SPREAD",
    market_status: "OPEN",
    last_updated: new Date().toISOString(),
  },
  NVDA: {
    symbol: "NVDA",
    name: "NVIDIA Corporation",
    price: 128.40,
    change: 3.12,
    change_percent: 2.49,
    high: 129.80,
    low: 125.60,
    volume: 82150000,
    realized_volatility: 34.50,
    implied_volatility: 48.20,
    iv_rv_ratio: 1.40,
    iv_premium: 39.7,
    opportunity_score: 82,
    market_regime: "EARNINGS HIGH IV",
    vol_signal: "EXPENSIVE",
    strategy: "IRON_CONDOR",
    market_status: "OPEN",
    last_updated: new Date().toISOString(),
  },
  AAPL: {
    symbol: "AAPL",
    name: "Apple Inc.",
    price: 228.60,
    change: 0.45,
    change_percent: 0.20,
    high: 229.40,
    low: 227.80,
    volume: 38200100,
    realized_volatility: 14.10,
    implied_volatility: 17.20,
    iv_rv_ratio: 1.22,
    iv_premium: 22.0,
    opportunity_score: 68,
    market_regime: "LOW SPREAD",
    vol_signal: "FAIR",
    strategy: "NO_TRADE",
    market_status: "OPEN",
    last_updated: new Date().toISOString(),
  },
  TSLA: {
    symbol: "TSLA",
    name: "Tesla Inc.",
    price: 218.80,
    change: -4.30,
    change_percent: -1.93,
    high: 224.50,
    low: 216.90,
    volume: 59300200,
    realized_volatility: 48.20,
    implied_volatility: 41.50,
    iv_rv_ratio: 0.86,
    iv_premium: -13.9,
    opportunity_score: 74,
    market_regime: "VOLATILITY COMPRESSED",
    vol_signal: "CHEAP",
    strategy: "LONG_STRADDLE",
    market_status: "OPEN",
    last_updated: new Date().toISOString(),
  },
  MSFT: {
    symbol: "MSFT",
    name: "Microsoft Corporation",
    price: 432.10,
    change: 2.80,
    change_percent: 0.65,
    high: 434.50,
    low: 429.80,
    volume: 21400000,
    realized_volatility: 13.50,
    implied_volatility: 16.90,
    iv_rv_ratio: 1.25,
    iv_premium: 25.2,
    opportunity_score: 64,
    market_regime: "FAIR VALUE",
    vol_signal: "FAIR",
    strategy: "NO_TRADE",
    market_status: "OPEN",
    last_updated: new Date().toISOString(),
  },
  AMZN: {
    symbol: "AMZN",
    name: "Amazon.com Inc.",
    price: 188.50,
    change: 1.40,
    change_percent: 0.75,
    high: 190.20,
    low: 187.10,
    volume: 34100000,
    realized_volatility: 18.20,
    implied_volatility: 24.80,
    iv_rv_ratio: 1.36,
    iv_premium: 36.3,
    opportunity_score: 79,
    market_regime: "MODERATE SPREAD",
    vol_signal: "EXPENSIVE",
    strategy: "BULL_PUT_SPREAD",
    market_status: "OPEN",
    last_updated: new Date().toISOString(),
  },
};
